parameters:
#    armd_report.example.class: Armd\ReportBundle\Example

services:
#    armd_report.example:
#        class: %armd_report.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    armd_employee.registration.form.type:
      class: Armd\ReportBundle\Form\RegistrationFormType
      tags:
       - { name: form.type, alias: armd_employee_registration }
