<?php

namespace Armd\ProjectBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeRepository extends EntityRepository
{
    public function findAll()
    {
         return $this->getEntityManager()
            ->createQuery('SELECT e FROM ArmdProjectBundle:Employee e ORDER BY e.surname ASC')
            ->getResult();
        //return parent::findAll();
    }
}