<?php

namespace Armd\ProjectBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
    public function findAll()
    {
         return $this->getEntityManager()
            ->createQuery('SELECT p FROM ArmdProjectBundle:Project p ORDER BY p.title ASC')
            ->getResult();
        //return parent::findAll();
    }
}