Armd\ProjectBundle\Entity\ProjectSubcontract:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    hours:
      type: integer
    title:
      type: string
    salary:
      type: integer
  manyToOne:
    subcontract:
      targetEntity: Armd\ProjectBundle\Entity\Subcontract
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        subcontract_id:
          referencedColumnName: id
          onDelete: SET NULL
      orphanRemoval: false
      
    project:
      targetEntity: Armd\ProjectBundle\Entity\Project
      cascade: {  }
      joinColumns:
        project_id:
          referencedColumnName: id
          onDelete: SET NULL
  
  lifecycleCallbacks: {  }
